/**
 * Saved games service
 *
 * Shared by every saved-games entry point. Phase A only has the browser
 * door (routes/savedGames.js, authenticated with the user's login token);
 * Phase D adds a chessServer door with a service key that calls the same
 * functions, so the rules below live here rather than in a route.
 *
 * Rules enforced here:
 *  - Every PGN is replayed with chess.js. An illegal move, a PGN that
 *    doesn't start from the game's starting position, or one over the move
 *    cap is rejected.
 *  - The server decides checkmate and draws from that replay. The browser
 *    can only claim a resignation.
 *  - Students read and write their own games. A mentor reads the games of
 *    the student they're paired with (checked at read time, so access ends
 *    when the mentorship does). Admins read all games.
 */

const { Chess, DEFAULT_POSITION } = require("chess.js");
const Users = require("../models/users");

// Caps are configurable until the per-student limit and retention decision
// is made (plan: "Decisions for Devin"). 600 plies is far beyond any real
// game; the PGN length cap stops oversized bodies before chess.js parses them.
const LIMITS = {
  maxPlies: parseInt(process.env.SAVED_GAMES_MAX_PLIES) || 600,
  maxGamesPerUser: parseInt(process.env.SAVED_GAMES_MAX_PER_USER) || 100,
  maxPgnLength: 20000,
};

class SavedGameError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

/**
 * Normalises a FEN through chess.js so equivalent spellings compare equal.
 * Throws a 400 for anything chess.js won't load.
 */
function normalizeFen(fen) {
  if (typeof fen !== "string" || !fen.trim()) {
    throw new SavedGameError(400, "startFen must be a FEN string");
  }
  try {
    return new Chess(fen.trim()).fen();
  } catch (_) {
    throw new SavedGameError(400, "startFen is not a valid position");
  }
}

/**
 * Replays `pgn` from `startFen` and returns the game state the server
 * stores. The returned `pgn` is regenerated by chess.js, so headers,
 * comments and any other free text the client sent are dropped.
 */
function replayPgn(pgn, startFen) {
  if (pgn === undefined || pgn === null) pgn = "";
  if (typeof pgn !== "string") {
    throw new SavedGameError(400, "pgn must be a string");
  }
  if (pgn.length > LIMITS.maxPgnLength) {
    throw new SavedGameError(400, "pgn is too long");
  }

  const game = new Chess(startFen);
  if (pgn.trim()) {
    const parsed = new Chess();
    try {
      parsed.loadPgn(pgn);
    } catch (_) {
      throw new SavedGameError(400, "pgn contains an illegal or unreadable move");
    }

    // A PGN without a FEN header starts from the standard position.
    const pgnStart = parsed.getHeaders().FEN || DEFAULT_POSITION;
    if (normalizeFen(pgnStart) !== startFen) {
      throw new SavedGameError(400, "pgn does not start from this game's starting position");
    }

    const moves = parsed.history();
    if (moves.length > LIMITS.maxPlies) {
      throw new SavedGameError(400, `games are limited to ${LIMITS.maxPlies} moves`);
    }
    for (const san of moves) game.move(san);
  }

  return {
    pgn: game.history().length ? game.pgn() : "",
    fen: game.fen(),
    plyCount: game.history().length,
    ...outcomeFor(game),
  };
}

/**
 * Result of the replayed position. `status` is from the owner's side,
 * which is filled in by the caller (see resultForPlayer).
 */
function outcomeFor(game) {
  if (game.isCheckmate()) {
    // The side to move has been mated.
    return { over: true, loserColor: game.turn() === "w" ? "white" : "black", endReason: "checkmate" };
  }
  if (game.isStalemate()) return { over: true, loserColor: null, endReason: "stalemate" };
  if (game.isInsufficientMaterial()) return { over: true, loserColor: null, endReason: "insufficient_material" };
  if (game.isThreefoldRepetition()) return { over: true, loserColor: null, endReason: "threefold_repetition" };
  if (game.isDrawByFiftyMoves()) return { over: true, loserColor: null, endReason: "fifty_move" };
  return { over: false, loserColor: null, endReason: null };
}

/** Turns a replay into the stored status/endReason for the game's owner. */
function resultForPlayer(replay, playerColor) {
  if (!replay.over) return { status: "ongoing", endReason: null };
  if (!replay.loserColor) return { status: "draw", endReason: replay.endReason };
  return {
    status: replay.loserColor === playerColor ? "lost" : "won",
    endReason: replay.endReason,
  };
}

function isOwner(user, game) {
  return Boolean(user && game && String(game.userId) === String(user._id));
}

/**
 * Whether `user` may read `game`. Owners and admins always can. A mentor can
 * if they and the game's owner are currently paired with each other; the
 * pairing is stored on both user records (see routes/users.js
 * /updateMentorship), so both sides are checked.
 */
async function canRead(user, game) {
  if (!user || !game) return false;
  if (isOwner(user, game)) return true;
  if (user.role === "admin") return true;
  if (user.role === "mentor" && user.mentorshipUsername) {
    const owner = await Users.findById(game.userId)
      .select("username mentorshipUsername")
      .lean();
    return Boolean(
      owner &&
        owner.username === user.mentorshipUsername &&
        owner.mentorshipUsername === user.username
    );
  }
  return false;
}

/** The fields a client sees. Never exposes the Mongo _id or userId. */
function toPublic(game) {
  return {
    uuid: game.uuid,
    gameType: game.gameType,
    gameName: game.gameName,
    playerColor: game.playerColor,
    computerLevel: game.computerLevel,
    startFen: game.startFen,
    pgn: game.pgn,
    fen: game.fen,
    plyCount: game.plyCount,
    status: game.status,
    endReason: game.endReason,
    notes: (game.notes || []).map((n) => ({
      ply: n.ply,
      authorUsername: n.authorUsername,
      text: n.text,
      createdAt: n.createdAt,
    })),
    createdAt: game.createdAt,
    updatedAt: game.updatedAt,
  };
}

/** The list view leaves out the move history and notes. */
function toSummary(game) {
  const { pgn, notes, ...summary } = toPublic(game);
  return summary;
}

module.exports = {
  LIMITS,
  SavedGameError,
  normalizeFen,
  replayPgn,
  resultForPlayer,
  isOwner,
  canRead,
  toPublic,
  toSummary,
  DEFAULT_POSITION,
};
